version: "3.9"
services:

  katersltc:
    #image: ubuntu:bionic
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      #- db-data:/var/lib/postgresql/data
      - ./katersltc:/root/.katersltc
    ports:
      - "6379"
      - "33701"
      - "33700"

volumes:
  katersltc:
